/** English word banks. Format: "A:Word,Word;B:Word,Word;..." */
export const enBanks: Record<string, string> = {
  city:
    "A:Amsterdam,Athens,Atlanta,Austin;B:Berlin,Boston,Barcelona,Brisbane;C:Chicago,Cardiff,Cairo,Copenhagen;D:Dublin,Dallas,Denver,Detroit;E:Edinburgh,El Paso,Essen;F:Florence,Frankfurt,Fresno;G:Glasgow,Geneva,Gothenburg;H:Houston,Hamburg,Helsinki,Hanoi;I:Istanbul,Indianapolis,Innsbruck;J:Jakarta,Jerusalem,Johannesburg;K:Kyoto,Krakow,Kiev,Kansas City;L:London,Lisbon,Liverpool,Los Angeles;M:Madrid,Manchester,Melbourne,Munich;N:New York,Naples,Nairobi,Nashville;O:Oslo,Osaka,Ottawa,Oxford;P:Paris,Prague,Portland,Perth;R:Rome,Rotterdam,Riga,Reykjavik;S:Sydney,Stockholm,Seattle,Seoul;T:Tokyo,Toronto,Turin,Tampa;U:Utrecht,Ulm,Udine;V:Vienna,Venice,Vancouver,Valencia;W:Warsaw,Washington,Wellington;Z:Zurich,Zagreb,Zaragoza",
  country:
    "A:Australia,Argentina,Austria,Albania;B:Brazil,Belgium,Bulgaria,Bolivia;C:Canada,China,Chile,Croatia;D:Denmark,Dominica,Djibouti;E:Egypt,Estonia,Ecuador,Ethiopia;F:France,Finland,Fiji;G:Germany,Greece,Ghana,Georgia;H:Hungary,Honduras,Haiti;I:Italy,India,Ireland,Iceland;J:Japan,Jamaica,Jordan;K:Kenya,Korea,Kuwait;L:Latvia,Lithuania,Luxembourg,Lebanon;M:Mexico,Malta,Morocco,Malaysia;N:Norway,Netherlands,Nepal,New Zealand;O:Oman;P:Poland,Portugal,Peru,Pakistan;R:Romania,Russia,Rwanda;S:Spain,Sweden,Switzerland,Slovenia;T:Turkey,Thailand,Tunisia,Tanzania;U:Uruguay,Ukraine,Uganda,USA;V:Vietnam,Venezuela;W:Wales;Z:Zambia,Zimbabwe",
  river:
    "A:Amazon,Avon,Amur,Arno;B:Brahmaputra,Bann,Blackwater;C:Colorado,Columbia,Congo,Clyde;D:Danube,Don,Dee,Dnieper;E:Euphrates,Elbe,Exe;F:Forth,Fraser,Flinders;G:Ganges,Garonne,Guadalquivir;H:Hudson,Humber,Huang He;I:Indus,Irrawaddy,Isar;J:Jordan,James,Jhelum;K:Kongo,Klamath,Kuban;L:Loire,Lena,Limpopo,Liffey;M:Mississippi,Missouri,Mekong,Murray;N:Nile,Niger,Neva,Neckar;O:Ohio,Ob,Oder,Orinoco;P:Po,Parana,Potomac;R:Rhine,Rhone,Rio Grande;S:Seine,Severn,Shannon,Saale;T:Thames,Tiber,Tigris,Trent;U:Ural,Usk,Uruguay;V:Volga,Vistula,Volta;W:Weser,Wye,Wabash;Z:Zambezi",
  name:
    "A:Alice,Adam,Amy,Aaron;B:Ben,Bella,Brian,Bianca;C:Chloe,Chris,Clara,Caleb;D:Daniel,Diana,David,Daisy;E:Emma,Ethan,Ella,Eric;F:Frank,Fiona,Felix,Faith;G:Grace,George,Gina,Gabriel;H:Hannah,Henry,Holly,Harry;I:Isabel,Ian,Ivy,Isaac;J:James,Julia,Jack,Jasmine;K:Kate,Kevin,Karen,Kyle;L:Lucy,Liam,Laura,Leo;M:Maria,Michael,Mia,Mark;N:Nina,Noah,Nathan,Nora;O:Oliver,Olivia,Oscar,Owen;P:Paul,Paula,Peter,Phoebe;R:Rachel,Ryan,Rose,Robert;S:Sarah,Sam,Sophie,Simon;T:Tom,Tina,Theo,Tara;U:Ursula,Ulysses,Uma;V:Victor,Vera,Violet,Vincent;W:William,Wendy,Walter;Z:Zoe,Zack,Zara",
  animal:
    "A:Ant,Antelope,Alligator,Ape;B:Bear,Bee,Badger,Buffalo;C:Cat,Cow,Camel,Crocodile;D:Dog,Dolphin,Deer,Duck;E:Elephant,Eagle,Eel,Emu;F:Fox,Frog,Falcon,Ferret;G:Giraffe,Goat,Gorilla,Goose;H:Horse,Hamster,Hippo,Hedgehog;I:Iguana,Ibis,Impala;J:Jaguar,Jellyfish,Jackal;K:Kangaroo,Koala,Kingfisher;L:Lion,Lizard,Llama,Lynx;M:Mouse,Monkey,Moose,Mole;N:Newt,Nightingale,Narwhal;O:Otter,Owl,Octopus,Ostrich;P:Penguin,Panda,Parrot,Pig;R:Rabbit,Rat,Raccoon,Rhino;S:Snake,Sheep,Squirrel,Shark;T:Tiger,Turtle,Toad,Tuna;U:Urchin,Uakari;V:Vulture,Viper,Vole;W:Wolf,Whale,Walrus,Wombat;Z:Zebra,Zebu",
  job:
    "A:Actor,Architect,Accountant,Astronaut;B:Baker,Builder,Butcher,Barber;C:Chef,Carpenter,Cashier,Coach;D:Doctor,Dentist,Driver,Designer;E:Engineer,Electrician,Editor;F:Farmer,Firefighter,Florist;G:Gardener,Guard,Geologist;H:Hairdresser,Historian,Host;I:Illustrator,Instructor,Inspector;J:Journalist,Judge,Janitor,Jeweller;K:Keeper,Knight;L:Lawyer,Librarian,Lifeguard;M:Mechanic,Musician,Manager,Miner;N:Nurse,Notary,Navigator;O:Optician,Officer,Operator;P:Pilot,Plumber,Painter,Programmer;R:Referee,Reporter,Receptionist;S:Scientist,Singer,Soldier,Surgeon;T:Teacher,Tailor,Translator,Therapist;U:Undertaker,Usher,Umpire;V:Vet,Violinist,Videographer;W:Waiter,Writer,Welder;Z:Zookeeper,Zoologist",
  plant:
    "A:Aloe,Ash,Azalea,Acacia;B:Bamboo,Birch,Basil,Bluebell;C:Cactus,Clover,Cedar,Chestnut;D:Daisy,Dandelion,Daffodil,Dahlia;E:Elm,Eucalyptus,Elder;F:Fern,Fig,Fir,Foxglove;G:Grass,Ginger,Geranium;H:Hazel,Holly,Hyacinth,Hemlock;I:Ivy,Iris,Ironwood;J:Jasmine,Juniper,Jute;K:Kale,Kelp,Kudzu;L:Lily,Lavender,Lotus,Lilac;M:Maple,Moss,Mint,Magnolia;N:Nettle,Narcissus,Nutmeg;O:Oak,Orchid,Olive,Oregano;P:Pine,Palm,Poppy,Parsley;R:Rose,Rosemary,Reed,Rhubarb;S:Sunflower,Sage,Spruce,Snowdrop;T:Tulip,Thyme,Thistle,Teak;U:Ulmus,Umbrella plant;V:Violet,Vine,Verbena;W:Willow,Wheat,Wisteria;Z:Zinnia,Zucchini plant",
  food:
    "A:Apple pie,Avocado,Asparagus;B:Bread,Burger,Bacon,Burrito;C:Cheese,Curry,Cake,Chips;D:Dumplings,Donut,Duck;E:Eggs,Enchilada,Eclair;F:Fish,Fries,Falafel;G:Gnocchi,Goulash,Granola;H:Hamburger,Honey,Hummus,Hot dog;I:Ice cream,Irish stew;J:Jam,Jelly,Jambalaya;K:Kebab,Ketchup,Kimchi;L:Lasagne,Lamb,Lentils;M:Meatballs,Muesli,Mango;N:Noodles,Nachos,Nuggets;O:Omelette,Olives,Oatmeal;P:Pizza,Pasta,Pancakes,Paella;R:Rice,Risotto,Ravioli,Ribs;S:Soup,Salad,Steak,Sushi;T:Toast,Tacos,Tofu,Tiramisu;U:Udon,Upside-down cake;V:Vanilla pudding,Veggie burger;W:Waffles,Wrap,Watermelon;Z:Ziti,Zucchini bread",
  color:
    "A:Amber,Aqua,Azure,Apricot;B:Blue,Black,Beige,Burgundy;C:Crimson,Cyan,Coral,Charcoal;D:Denim,Dark green;E:Emerald,Ecru,Eggshell;F:Fuchsia,Forest green,Flamingo;G:Green,Gold,Grey,Gunmetal;H:Hazel,Honey;I:Indigo,Ivory;J:Jade,Jet black;K:Khaki,Kelly green;L:Lime,Lilac,Lavender,Lemon;M:Magenta,Maroon,Mint,Mustard;N:Navy,Nude;O:Orange,Olive,Ochre;P:Pink,Purple,Peach,Plum;R:Red,Rose,Ruby,Rust;S:Silver,Scarlet,Sapphire,Salmon;T:Turquoise,Teal,Tan,Taupe;U:Ultramarine,Umber;V:Violet,Vermilion;W:White,Wine;Z:Zaffre",
  brand:
    "A:Apple,Adidas,Amazon,Audi;B:BMW,Burger King,Bosch;C:Coca-Cola,Chanel,Canon,Converse;D:Dell,Disney,Dyson,Dove;E:Ebay,Esso,Evian;F:Ford,Fanta,Fila,Fender;G:Google,Gucci,Gillette;H:Honda,HP,Heinz,H&M;I:IKEA,Intel,Instagram;J:Jaguar,Jeep,Jack Daniels;K:Kodak,KFC,Kellogg,Kia;L:Lego,Levis,Lenovo,Lidl;M:Microsoft,McDonalds,Mars;N:Nike,Nokia,Nintendo,Netflix;O:Oreo,Oral-B,Oracle;P:Pepsi,Puma,Philips,Prada;R:Rolex,Reebok,Red Bull;S:Samsung,Sony,Starbucks,Shell;T:Toyota,Tesla,Twitter,Toshiba;U:Uber,Uniqlo,Under Armour;V:Volvo,Visa,Vans,Volkswagen;W:Walmart,Whirlpool,WhatsApp;Z:Zara,Zalando,Zoom",
  band:
    "A:ABBA,AC/DC,Adele,Arctic Monkeys;B:Beatles,Beyonce,Blur,Bon Jovi;C:Coldplay,Cure,Cardi B;D:Daft Punk,Drake,Doors;E:Eminem,Ed Sheeran,Eagles;F:Foo Fighters,Fleetwood Mac;G:Green Day,Gorillaz,Guns N Roses;H:Hozier,Harry Styles;I:Imagine Dragons,Iron Maiden;J:Jay-Z,Jackson Five,Joy Division;K:Kiss,Kings of Leon,Kanye West;L:Linkin Park,Lady Gaga,Led Zeppelin;M:Madonna,Metallica,Muse;N:Nirvana,Nickelback,Nine Inch Nails;O:Oasis,OutKast,OneRepublic;P:Pink Floyd,Prince,Pearl Jam;Q:Queen;R:Radiohead,Rihanna,Rolling Stones;S:Sia,Sting,Spice Girls;T:The Weeknd,Taylor Swift,Toto;U:U2,Usher,Underworld;V:Van Halen,Vampire Weekend;W:Weezer,Wu-Tang Clan,Whitney Houston;Z:ZZ Top,Zayn",
  movie:
    "A:Avatar,Avengers,Alien,Aladdin;B:Batman,Barbie,Braveheart;C:Casablanca,Coco,Cars,Chicago;D:Dune,Django,Dunkirk;E:Elf,Everest,Enola Holmes;F:Frozen,Fight Club,Forrest Gump;G:Gladiator,Ghostbusters,Grease;H:Harry Potter,Hangover,Her;I:Inception,Interstellar,Ice Age;J:Jaws,Joker,Jurassic Park;K:King Kong,Knives Out;L:La La Land,Lion King,Logan;M:Matrix,Moana,Minions;N:Nemo,Nope,Notting Hill;O:Oppenheimer,Oblivion,Oceans Eleven;P:Parasite,Psycho,Pulp Fiction;R:Rocky,Ratatouille,Rambo;S:Shrek,Star Wars,Spiderman;T:Titanic,Toy Story,Terminator;U:Up,Unforgiven,Uncut Gems;V:Venom,Vertigo,Vaiana;W:WALL-E,Whiplash,Wonka;Z:Zootopia,Zodiac,Zombieland",
  series:
    "A:Arrow,Alias,Atlanta;B:Breaking Bad,Better Call Saul,Bridgerton;C:Chernobyl,Cheers,Cobra Kai;D:Dexter,Dark,Downton Abbey;E:ER,Euphoria,Entourage;F:Friends,Fargo,Frasier;G:Game of Thrones,Glee,Gossip Girl;H:House,Heroes,Homeland;I:Industry,Invincible;J:Jessica Jones,Jack Ryan;K:Killing Eve,Knight Rider;L:Lost,Lucifer,Loki;M:Mad Men,Modern Family,Mandalorian;N:Narcos,New Girl,Normal People;O:Ozark,Outlander,Outer Banks;P:Peaky Blinders,Prison Break;R:Rick and Morty,Rome;S:Sherlock,Succession,Severance;T:True Detective,Ted Lasso;U:Umbrella Academy;V:Vikings,Veep;W:Westworld,Wednesday,White Lotus;Z:Z Nation",
  sport:
    "A:Athletics,Archery,American football;B:Basketball,Baseball,Boxing,Badminton;C:Cricket,Cycling,Climbing,Curling;D:Diving,Darts,Dressage;E:Equestrian,Endurance running;F:Football,Fencing,Figure skating;G:Golf,Gymnastics,Go-karting;H:Hockey,Handball,Hurdles;I:Ice hockey,Ice skating;J:Judo,Jogging,Javelin;K:Karate,Kayaking,Kickboxing;L:Lacrosse,Long jump,Luge;M:Marathon,Motocross,MMA;N:Netball,Nordic skiing;O:Orienteering,Olympic lifting;P:Polo,Pole vault,Parkour;R:Rugby,Rowing,Running;S:Swimming,Skiing,Surfing,Squash;T:Tennis,Table tennis,Triathlon;U:Ultimate frisbee;V:Volleyball,Vaulting;W:Wrestling,Water polo,Windsurfing;Z:Zumba",
  bodypart:
    "A:Arm,Ankle,Abdomen,Artery;B:Back,Brain,Bone,Belly;C:Chest,Chin,Cheek,Collarbone;D:Diaphragm,Duodenum;E:Ear,Elbow,Eye,Eyebrow;F:Foot,Finger,Forehead,Femur;G:Gum,Gut,Groin;H:Hand,Head,Heart,Hip;I:Intestine,Iris,Index finger;J:Jaw,Joint,Jugular;K:Knee,Kidney,Knuckle;L:Leg,Lung,Liver,Lip;M:Mouth,Muscle,Molar;N:Nose,Neck,Nail,Nerve;O:Organ,Oesophagus;P:Palm,Pelvis,Pupil;R:Rib,Retina,Ring finger;S:Shoulder,Skin,Spine,Stomach;T:Thumb,Tongue,Tooth,Toe;U:Uvula,Ulna;V:Vein,Vertebra;W:Wrist,Waist;Z:Zygomatic bone",
  object:
    "A:Anchor,Alarm clock,Apron;B:Book,Bottle,Broom,Bucket;C:Chair,Cup,Comb,Candle;D:Desk,Drill,Door,Dustpan;E:Envelope,Eraser,Easel;F:Fork,Fan,Flashlight,Frame;G:Glass,Glue,Guitar,Globe;H:Hammer,Hat,Hose,Hanger;I:Iron,Ink pot;J:Jar,Jug,Jigsaw;K:Key,Kettle,Knife;L:Lamp,Ladder,Laptop,Lighter;M:Mirror,Mug,Mop,Magnet;N:Needle,Notebook,Nail;O:Oven,Organiser;P:Pen,Pillow,Plate,Pan;R:Ruler,Radio,Rope,Rug;S:Scissors,Spoon,Suitcase,Sponge;T:Table,Towel,Torch,Teapot;U:Umbrella,USB stick;V:Vase,Vacuum,Van;W:Watch,Wallet,Whistle;Z:Zipper,Zip tie",
  clothing:
    "A:Anorak,Apron,Ascot;B:Blouse,Boots,Belt,Blazer;C:Coat,Cardigan,Cap,Chinos;D:Dress,Dungarees,Dressing gown;E:Earmuffs,Espadrilles;F:Fleece,Flip-flops,Frock;G:Gloves,Gown,Gilet;H:Hat,Hoodie,Heels;I:Insoles;J:Jacket,Jeans,Jumper,Jumpsuit;K:Kilt,Kimono,Kaftan;L:Leggings,Loafers,Leather jacket;M:Mittens,Mac,Miniskirt;N:Nightgown,Necktie;O:Overalls,Onesie;P:Pants,Pyjamas,Parka,Poncho;R:Raincoat,Robe,Romper;S:Shirt,Skirt,Socks,Sweater;T:T-shirt,Trousers,Tie,Trainers;U:Underwear,Uniform;V:Vest,Veil;W:Waistcoat,Wellies,Windbreaker;Z:Zip-up hoodie",
  carbrand:
    "A:Audi,Aston Martin,Alfa Romeo,Acura;B:BMW,Bentley,Bugatti,Buick;C:Chevrolet,Citroen,Chrysler,Cadillac;D:Dodge,Dacia,Daihatsu;E:Eagle,Edsel;F:Ford,Ferrari,Fiat,Fisker;G:GMC,Genesis,Geely;H:Honda,Hyundai,Hummer;I:Infiniti,Isuzu;J:Jaguar,Jeep;K:Kia,Koenigsegg;L:Lexus,Lamborghini,Land Rover,Lotus;M:Mercedes,Mazda,Mini,McLaren;N:Nissan,Nio;O:Opel,Oldsmobile;P:Porsche,Peugeot,Polestar;R:Renault,Rolls-Royce,Rivian;S:Subaru,Suzuki,Seat,Skoda;T:Toyota,Tesla,Tata;V:Volvo,Volkswagen,Vauxhall;W:Wiesmann,Willys;Z:Zastava",
  drink:
    "A:Apple juice,Americano,Ale;B:Beer,Brandy,Bubble tea;C:Coffee,Cola,Cider,Cappuccino;D:Daiquiri,Dr Pepper;E:Espresso,Eggnog,Energy drink;F:Fanta,Fizzy water,Frappe;G:Gin,Grape juice,Green tea;H:Hot chocolate,Highball;I:Iced tea,Irish coffee;J:Juice,Jack and coke;K:Kombucha,Kefir,Kir;L:Lemonade,Latte,Lager;M:Milk,Mojito,Martini,Milkshake;N:Negroni,Nectar;O:Orange juice,Ouzo;P:Prosecco,Punch,Pina colada;R:Rum,Rose wine,Root beer;S:Soda,Smoothie,Sangria;T:Tea,Tequila,Tonic;U:Ultra-filtered milk;V:Vodka,Vermouth;W:Water,Wine,Whisky;Z:Zinfandel",
  hobby:
    "A:Angling,Archery,Astronomy;B:Baking,Birdwatching,Blogging;C:Cooking,Camping,Chess,Cycling;D:Dancing,Drawing,Diving,DIY;E:Embroidery,Exploring;F:Fishing,Football,Fencing;G:Gardening,Gaming,Golf;H:Hiking,Horse riding,Hunting;I:Ice skating,Improv;J:Jogging,Juggling,Journalling;K:Knitting,Kayaking,Karaoke;L:Lego building,Learning languages,Listening to podcasts;M:Music,Meditation,Modelling;N:Needlework,Nordic walking;O:Origami,Orienteering;P:Painting,Pottery,Puzzles,Podcasting;R:Running,Reading,Rock climbing;S:Swimming,Singing,Skating,Sewing;T:Travelling,Tennis,Theatre;U:Ukulele,Upcycling;V:Volleyball,Volunteering;W:Walking,Writing,Woodworking;Z:Zumba,Zoology",
  subject:
    "A:Art,Algebra,Astronomy;B:Biology,Business studies;C:Chemistry,Computing,Chinese;D:Drama,Design,Dance;E:English,Economics,Engineering;F:French,Fine art,Fitness;G:Geography,German,Geology;H:History,Health,Home economics;I:Italian,IT,Informatics;J:Japanese,Journalism;K:Kinesiology;L:Latin,Literature,Law;M:Maths,Music,Media studies;N:Natural sciences,Nutrition;O:Orchestra,Oceanography;P:Physics,PE,Psychology,Philosophy;R:Religion,Robotics,Russian;S:Science,Spanish,Sociology,Statistics;T:Technology,Theatre,Trigonometry;U:Urban studies;V:Visual arts;W:Woodwork,World history,Writing;Z:Zoology",
  superhero:
    "A:Aquaman,Ant-Man,Aurora;B:Batman,Black Widow,Black Panther;C:Captain America,Catwoman,Cyclops;D:Daredevil,Deadpool,Doctor Strange;E:Elektra,Elastigirl;F:Flash,Falcon,Firestorm;G:Green Lantern,Gamora,Groot;H:Hulk,Hawkeye,Hellboy;I:Iron Man,Invisible Woman;J:Jean Grey,Jessica Jones;K:Kitty Pryde,Kick-Ass;L:Luke Cage,Loki;M:Magneto,Mystique,Moon Knight;N:Nightcrawler,Nick Fury;O:Oracle,Omni-Man;P:Professor X,Punisher;R:Robin,Rogue,Rocket;S:Superman,Spider-Man,Storm;T:Thor,Thing,Tempest;U:Ultron,Union Jack;V:Vision,Venom;W:Wonder Woman,Wolverine,Wasp;Z:Zatanna,Zoom",
  game:
    "A:Azul,Articulate,Anagrams;B:Backgammon,Blackjack,Bingo;C:Chess,Cluedo,Catan,Codenames;D:Draughts,Dominoes,Dixit;E:Exploding Kittens;F:Frisbee,Four in a row;G:Go,Guess Who,Gin rummy;H:Hangman,Hide and seek,Hearts;I:I spy,Imaginarium;J:Jenga,Jigsaw,Jackbox;K:Kerplunk,Kalah;L:Ludo,Labyrinth;M:Monopoly,Mahjong,Mastermind;N:Nine men morris;O:Othello,Operation;P:Poker,Pictionary,Pandemic;R:Risk,Rummy,Rummikub;S:Scrabble,Sudoku,Solitaire;T:Twister,Tag,Trivial Pursuit;U:Uno,Ultimate frisbee;V:Volleyball;W:Werewolf,Whist;Z:Zombicide",
  instrument:
    "A:Accordion,Alto sax,Autoharp;B:Bass,Banjo,Bagpipes,Bassoon;C:Cello,Clarinet,Cymbals,Conga;D:Drums,Didgeridoo,Double bass;E:Electric guitar,Euphonium;F:Flute,French horn,Fiddle;G:Guitar,Glockenspiel,Gong;H:Harp,Harmonica,Harpsichord;I:Irish bouzouki;J:Jaw harp,Jazz guitar;K:Keyboard,Kalimba,Kettledrum;L:Lute,Lyre;M:Mandolin,Marimba,Maracas;N:Nyckelharpa;O:Organ,Oboe,Ocarina;P:Piano,Piccolo,Panpipes;R:Recorder,Rattle;S:Saxophone,Sitar,Synthesizer;T:Trumpet,Trombone,Triangle,Tuba;U:Ukulele,Udu;V:Violin,Viola,Vibraphone;W:Whistle,Washboard;Z:Zither",
  sweet:
    "A:After Eight,Apple pie;B:Brownie,Biscuit,Bubblegum;C:Chocolate,Cookie,Candy floss;D:Donut,Digestive;E:Eclair,Easter egg;F:Fudge,Flapjack;G:Gummy bears,Gingerbread;H:Honeycomb,Humbug;I:Ice cream,Iced bun;J:Jelly beans,Jaffa cake;K:KitKat,Kinder egg;L:Lollipop,Liquorice;M:Marshmallow,Macaron,M&Ms;N:Nougat,Nutella;O:Oreo,Orange cream;P:Praline,Popcorn,Pudding;R:Rocky road,Rolo;S:Snickers,Sherbet,Shortbread;T:Toffee,Twix,Truffle;U:Unicorn cake;V:Vanilla ice cream;W:Waffle,Wine gums;Z:Zebra cake",
  furniture:
    "A:Armchair,Armoire;B:Bed,Bookshelf,Bench,Bar stool;C:Chair,Couch,Cupboard,Coffee table;D:Desk,Dresser,Divan;E:Easy chair,End table;F:Futon,Footstool,Filing cabinet;G:Garden chair,Glass table;H:Hammock,High chair,Hall stand;I:Island unit;J:Jewellery cabinet;K:Kitchen table,King bed;L:Lamp table,Loveseat,Lowboard;M:Mattress,Mirror cabinet;N:Nightstand,Nest of tables;O:Ottoman,Office chair;P:Piano stool,Pouffe;R:Rocking chair,Rack,Recliner;S:Sofa,Stool,Shelf,Sideboard;T:Table,Trunk,TV stand;U:Under-bed drawer;V:Vanity,Vitrine;W:Wardrobe,Writing desk;Z:Z-bed",
  island:
    "A:Aruba,Antigua,Azores;B:Bali,Barbados,Bermuda,Borneo;C:Corsica,Crete,Cuba,Cyprus;D:Dominica,Djerba;E:Easter Island,Elba;F:Fiji,Formentera,Faroe;G:Greenland,Guam,Gotland;H:Hawaii,Hispaniola,Hainan;I:Iceland,Ibiza,Ireland;J:Jamaica,Java,Jersey;K:Kauai,Kos,Kiribati;L:Lanzarote,Lesbos,Luzon;M:Madagascar,Majorca,Malta,Maui;N:Newfoundland,Nantucket;O:Okinawa,Oahu,Orkney;P:Phuket,Puerto Rico,Palawan;R:Rhodes,Reunion,Rugen;S:Sicily,Sardinia,Santorini,Sumatra;T:Tenerife,Tasmania,Tahiti;U:Ushant,Unst;V:Vancouver Island,Vis;W:Wight,Wangerooge;Z:Zanzibar,Zakynthos",
  capital:
    "A:Athens,Amsterdam,Ankara,Abuja;B:Berlin,Brussels,Budapest,Bern;C:Canberra,Cairo,Copenhagen,Caracas;D:Dublin,Doha,Dhaka,Damascus;E:Edinburgh;F:Freetown,Funafuti;G:Georgetown,Gaborone;H:Helsinki,Havana,Hanoi,Harare;I:Islamabad;J:Jakarta,Jerusalem,Juba;K:Kyiv,Kabul,Kingston,Kampala;L:London,Lisbon,Lima,Luxembourg;M:Madrid,Moscow,Manila,Mexico City;N:Nairobi,New Delhi,Nicosia;O:Oslo,Ottawa;P:Paris,Prague,Pretoria,Panama City;R:Rome,Riga,Riyadh,Reykjavik;S:Stockholm,Seoul,Sofia,Santiago;T:Tokyo,Tunis,Tallinn,Tehran;U:Ulaanbaatar;V:Vienna,Vilnius,Valletta;W:Warsaw,Washington,Wellington;Z:Zagreb",
  videogame:
    "A:Among Us,Assassins Creed,Apex Legends;B:Battlefield,Bloodborne,Bioshock;C:Call of Duty,Counter-Strike,Cyberpunk;D:Doom,Diablo,Dark Souls;E:Elden Ring,Elder Scrolls;F:Fortnite,FIFA,Far Cry,Fall Guys;G:GTA,God of War,Genshin Impact;H:Halo,Hades,Hollow Knight;I:It Takes Two;J:Just Cause,Journey;K:Kingdom Hearts;L:League of Legends,Last of Us;M:Minecraft,Mario Kart,Mass Effect;N:Need for Speed,No Mans Sky;O:Overwatch,Oblivion;P:Portal,Pokemon,Pac-Man;R:Rocket League,Roblox,Rust;S:Skyrim,Sims,Starfield,Stardew Valley;T:Tetris,Tomb Raider,Terraria;U:Uncharted,Undertale;V:Valorant,Valheim;W:Witcher,World of Warcraft;Z:Zelda,Zuma",
  tool:
    "A:Axe,Awl,Anvil;B:Bolt cutter,Brush,Bradawl;C:Chisel,Clamp,Crowbar;D:Drill,Dremel,Dustpan;E:Extension cord,Edge trimmer;F:File,Funnel,Flashlight;G:Grinder,Glue gun,Gouge;H:Hammer,Hacksaw,Hoe;I:Impact driver;J:Jigsaw,Jack;K:Knife,Key set;L:Level,Ladder,Lathe;M:Mallet,Multitool,Measuring tape;N:Nail gun,Nut driver;O:Oil can,Orbital sander;P:Pliers,Plane,Pickaxe;R:Ratchet,Rasp,Router;S:Screwdriver,Saw,Sander,Spanner;T:Torque wrench,Trowel,Tape measure;U:Utility knife;V:Vice,Vice grips;W:Wrench,Wheelbarrow,Workbench;Z:Z-clamp",
  feeling:
    "A:Anger,Anxiety,Awe,Affection;B:Boredom,Bliss,Bitterness;C:Calm,Confusion,Curiosity;D:Disgust,Delight,Despair;E:Envy,Excitement,Embarrassment;F:Fear,Frustration,Fondness;G:Gratitude,Guilt,Grief,Glee;H:Happiness,Hope,Hatred,Homesickness;I:Irritation,Insecurity;J:Joy,Jealousy;K:Kindness;L:Love,Loneliness,Longing;M:Melancholy,Motivation;N:Nostalgia,Nervousness;O:Optimism,Outrage;P:Pride,Panic,Peace;R:Relief,Regret,Resentment;S:Sadness,Shame,Surprise;T:Trust,Tension,Tenderness;U:Unease,Uncertainty;V:Vulnerability;W:Worry,Wonder,Warmth;Z:Zeal",
  generic:
    "A:Anchor,Apple,Arrow,Ant,Attic;B:Ball,Bridge,Book,Bell,Branch;C:Cloud,Candle,Cave,Clock,Coin;D:Door,Drum,Dust,Dream,Desk;E:Egg,Engine,Echo,Edge,Elbow;F:Fire,Flower,Fence,Feather,Frame;G:Garden,Glass,Gate,Ghost,Gift;H:House,Hill,Hook,Harbour,Hat;I:Island,Iron,Ice,Idea,Ink;J:Jar,Journey,Jewel,Jungle;K:Key,Kite,Knot,Kitchen;L:Lamp,Lake,Ladder,Leaf,Letter;M:Moon,Mountain,Mirror,Market,Map;N:Night,Needle,Nest,North,Note;O:Ocean,Oven,Orbit,Oak;P:Paper,Path,Pocket,Planet,Pillar;R:River,Rope,Roof,Ring,Rain;S:Sun,Star,Stone,Shadow,Street;T:Tower,Tree,Table,Train,Thread;U:Umbrella,Uniform,Universe;V:Valley,Vase,Voice,Village;W:Wind,Window,Water,Wall,Wheel;Z:Zone,Zebra crossing,Zip",
};
