/** Italian word banks. Format: "A:Parola,Parola;B:Parola,Parola;..." */
export const itBanks: Record<string, string> = {
  city:
    "A:Ancona,Asti,Alessandria,Amsterdam;B:Bologna,Bari,Bergamo,Berlino;C:Catania,Como,Cagliari,Cremona;D:Dublino,Dortmund,Domodossola;E:Empoli,Enna,Edimburgo;F:Firenze,Ferrara,Foggia,Francoforte;G:Genova,Grosseto,Ginevra,Gorizia;I:Imola,Imperia,Istanbul,Innsbruck;L:Lecce,Livorno,Lucca,Londra;M:Milano,Modena,Messina,Mantova;N:Napoli,Novara,Nizza,Nuoro;O:Oristano,Olbia,Oslo,Osaka;P:Palermo,Padova,Perugia,Pisa;Q:Quarto,Quartu;R:Roma,Rimini,Ravenna,Reggio Calabria;S:Siena,Salerno,Sassari,Savona;T:Torino,Trieste,Trento,Treviso;U:Udine,Urbino,Utrecht;V:Venezia,Verona,Vicenza,Varese;Z:Zagabria,Zurigo",
  country:
    "A:Austria,Albania,Argentina,Australia;B:Belgio,Brasile,Bulgaria,Bolivia;C:Cina,Cile,Croazia,Canada;D:Danimarca,Dominica;E:Egitto,Estonia,Ecuador,Etiopia;F:Francia,Finlandia,Filippine;G:Germania,Grecia,Ghana,Giappone;I:Italia,India,Irlanda,Islanda;L:Lussemburgo,Lettonia,Lituania,Libano;M:Messico,Malta,Marocco,Malesia;N:Norvegia,Nepal,Nigeria,Nuova Zelanda;O:Olanda,Oman;P:Polonia,Portogallo,Perù,Pakistan;Q:Qatar;R:Romania,Russia,Ruanda;S:Spagna,Svezia,Svizzera,Slovenia;T:Turchia,Thailandia,Tunisia,Tanzania;U:Ungheria,Uruguay,Ucraina,Uganda;V:Vietnam,Venezuela;Z:Zambia,Zimbabwe",
  river:
    "A:Adige,Arno,Aniene,Amazzoni;B:Brenta,Bormida,Basento;C:Chienti,Cesano,Congo;D:Danubio,Dora Baltea,Don;E:Esino,Elba,Eufrate;F:Foglia,Fortore,Flumendosa;G:Garigliano,Gange,Gari;I:Isonzo,Indo,Idice;L:Lambro,Livenza,Loira;M:Mincio,Metauro,Mississippi;N:Nera,Nilo,Neva;O:Ombrone,Oglio,Orinoco;P:Po,Piave,Panaro,Parana;R:Reno,Rodano,Reggia;S:Sarno,Secchia,Senna,Sile;T:Tevere,Tanaro,Ticino,Tamigi;V:Volturno,Volga,Vistola;Z:Zambesi",
  name:
    "A:Anna,Alessandro,Andrea,Aurora;B:Beatrice,Bruno,Bianca,Bernardo;C:Chiara,Carlo,Camilla,Cristina;D:Davide,Daniela,Diego,Dario;E:Elena,Enrico,Emma,Elisa;F:Francesca,Federico,Filippo,Fabio;G:Giulia,Giovanni,Giorgio,Greta;I:Irene,Ivan,Ilaria,Ignazio;L:Luca,Laura,Lorenzo,Lucia;M:Marco,Maria,Matteo,Martina;N:Nicola,Noemi,Nadia,Nino;O:Ottavio,Olga,Orlando;P:Paolo,Paola,Pietro,Piera;Q:Quirino;R:Roberto,Rita,Riccardo,Rosa;S:Sara,Simone,Silvia,Stefano;T:Teresa,Tommaso,Tiziano;U:Umberto,Ursula,Ugo;V:Valentina,Vittorio,Viola;Z:Zeno,Zaira",
  animal:
    "A:Aquila,Ape,Asino,Anatra;B:Balena,Bufalo,Bradipo,Barbagianni;C:Cane,Cavallo,Coniglio,Coccodrillo;D:Delfino,Daino,Dromedario;E:Elefante,Ermellino,Elce;F:Formica,Foca,Falco,Farfalla;G:Gatto,Gallo,Giraffa,Gorilla;I:Ippopotamo,Iena,Istrice;L:Leone,Lupo,Lucertola,Lepre;M:Mucca,Maiale,Marmotta,Merlo;N:Nutria,Narvalo;O:Orso,Oca,Orata,Ornitorinco;P:Pecora,Pinguino,Pappagallo,Pesce;Q:Quaglia;R:Rana,Riccio,Rondine,Ragno;S:Scimmia,Serpente,Squalo,Struzzo;T:Tigre,Tartaruga,Topo,Tasso;U:Usignolo,Upupa;V:Vipera,Volpe,Vitello;Z:Zebra,Zanzara",
  job:
    "A:Avvocato,Architetto,Attore,Autista;B:Barista,Bidello,Bagnino;C:Cuoco,Cameriere,Contadino,Commesso;D:Dentista,Dottore,Designer;E:Elettricista,Estetista,Editore;F:Falegname,Fornaio,Fotografo,Fabbro;G:Giardiniere,Giornalista,Giudice;I:Infermiere,Ingegnere,Insegnante;L:Libraio,Logopedista;M:Medico,Meccanico,Muratore,Macellaio;N:Notaio,Nutrizionista;O:Operaio,Ottico,Orafo;P:Professore,Pilota,Pittore,Pescatore;Q:Questore;R:Ricercatore,Regista,Ragioniere;S:Sarto,Scrittore,Scienziato,Segretario;T:Tassista,Traduttore,Tecnico;U:Ufficiale,Urbanista;V:Veterinario,Vigile,Venditore;Z:Zoologo",
  plant:
    "A:Acacia,Abete,Alloro,Aloe;B:Betulla,Basilico,Bambù,Bucaneve;C:Ciliegio,Castagno,Cactus,Camomilla;D:Dalia,Digitale;E:Edera,Eucalipto,Erica;F:Felce,Faggio,Fico,Finocchio;G:Gelsomino,Geranio,Girasole,Ginepro;I:Ibisco,Iris,Ippocastano;L:Lavanda,Lillà,Loto,Limone;M:Menta,Margherita,Melo,Mimosa;N:Narciso,Noce,Ninfea;O:Orchidea,Olivo,Origano,Ontano;P:Pino,Pioppo,Papavero,Prezzemolo;Q:Quercia;R:Rosa,Rosmarino,Rovere,Rododendro;S:Salvia,Salice,Sequoia,Stella alpina;T:Tulipano,Tiglio,Timo;U:Ulivo,Ulmo;V:Viola,Vite,Verbena;Z:Zafferano,Zucca",
  food:
    "A:Arancini,Arrosto,Amatriciana;B:Bruschetta,Bistecca,Brodo;C:Carbonara,Cotoletta,Caprese;D:Dolce,Doner;E:Empanada,Erbazzone;F:Focaccia,Frittata,Fagioli;G:Gnocchi,Gelato,Grigliata;I:Insalata,Involtini;L:Lasagne,Lenticchie,Linguine;M:Minestrone,Mozzarella,Mortadella;N:Nduja,Nutella;O:Orecchiette,Omelette;P:Pizza,Pasta,Polenta,Panino;Q:Quiche;R:Risotto,Ravioli,Ragù;S:Spaghetti,Saltimbocca,Sushi;T:Tiramisù,Tortellini,Trippa;U:Uova,Uva;V:Vitello tonnato,Verdure;Z:Zuppa,Zucchine,Ziti",
  color:
    "A:Azzurro,Ambra,Avorio,Antracite;B:Bianco,Blu,Beige,Bordeaux;C:Ciano,Corallo,Carminio;D:Dorato;E:Ebano,Ecrù,Erba;F:Fucsia,Fumo;G:Giallo,Grigio,Granata;I:Indaco,Iris;L:Lilla,Lime,Lavanda;M:Marrone,Magenta,Menta;N:Nero,Nocciola,Notte;O:Oro,Ocra,Oliva,Oltremare;P:Porpora,Platino,Pesca;R:Rosso,Rosa,Rubino,Ruggine;S:Salmone,Smeraldo,Senape;T:Turchese,Tortora,Terracotta;U:Ultravioletto;V:Verde,Viola,Vermiglio;Z:Zafferano",
  brand:
    "A:Adidas,Apple,Amazon,Armani;B:Barilla,Bialetti,Bulgari;C:Coca-Cola,Chanel,Campari;D:Dolce e Gabbana,Diesel,Dyson;E:Esselunga,Eni,Ebay;F:Ferrero,Fila,Fiat,Fanta;G:Gucci,Google,Geox;I:Ikea,Illy,Invicta;L:Lego,Lavazza,Levis,Lidl;M:Mulino Bianco,Microsoft,Mutti;N:Nike,Nutella,Nintendo,Netflix;O:Oreo,Olivetti,Omsa;P:Prada,Puma,Pepsi,Peroni;Q:Quechua;R:Rolex,Rana,Red Bull;S:Samsung,Sony,San Pellegrino;T:Tesla,Toyota,Tim;U:Uber,Unieuro;V:Versace,Vodafone,Volvo;Z:Zara,Zalando,Zanussi",
  band:
    "A:ABBA,Adele,AC/DC,Annalisa;B:Beatles,Baglioni,Blanco;C:Coldplay,Cremonini,Caparezza;D:Depeche Mode,Drake,Diodato;E:Elisa,Eminem,Elio;F:Fedez,Franco Battiato,Fabri Fibra;G:Gazzelle,Green Day,Guns N Roses;I:Irama,Imagine Dragons;L:Ligabue,Laura Pausini,Linkin Park;M:Maneskin,Madonna,Mengoni,Metallica;N:Negramaro,Nirvana,Nek;O:Oasis,Ornella Vanoni;P:Pink Floyd,Pooh,Pinguini Tattici Nucleari;Q:Queen;R:Ramazzotti,Rihanna,Radiohead;S:Subsonica,Sting,Sfera Ebbasta;T:Tiziano Ferro,The Weeknd;U:U2,Ultimo,Usher;V:Vasco Rossi,Vinicio Capossela;Z:Zucchero,ZZ Top",
  movie:
    "A:Avatar,Avengers,Aladdin;B:Batman,Barbie,Bianca;C:Casablanca,Cars,Coco;D:Dune,Django,Dracula;E:Ercole,Everest;F:Frozen,Forrest Gump;G:Gladiatore,Ghostbusters;I:Inception,Interstellar;L:La Dolce Vita,Lo Squalo,La La Land;M:Matrix,Mamma Mia,Minions;N:Nemo,Notting Hill;O:Oppenheimer,Oceans Eleven;P:Parasite,Pinocchio,Pulp Fiction;Q:Quo Vado;R:Rocky,Ratatouille,Roma;S:Shrek,Star Wars,Spiderman;T:Titanic,Toy Story,Terminator;U:Up,Uomo Ragno;V:Venom,Vertigine;Z:Zootropolis,Zodiac",
  series:
    "A:Arrow,Amici;B:Breaking Bad,Boris,Black Mirror;C:Chernobyl,Csi;D:Dark,Dexter,Doc;E:Euphoria,Elite;F:Friends,Fargo,Fringe;G:Game of Thrones,Gomorra;I:Il Commissario Montalbano,Industry;L:Lost,Lucifer,La Casa di Carta;M:Mare Fuori,Mad Men,Mandalorian;N:Narcos,Naruto;O:Ozark,One Piece;P:Peaky Blinders,Prison Break;R:Rick and Morty,Romanzo Criminale;S:Suburra,Stranger Things,Sherlock;T:The Office,Ted Lasso;U:Umbrella Academy;V:Vikings,Vis a Vis;Z:Zorro",
  sport:
    "A:Atletica,Arrampicata,Arti marziali;B:Basket,Boxe,Badminton,Baseball;C:Calcio,Ciclismo,Canottaggio,Canoa;D:Danza sportiva,Dressage;E:Equitazione,Enduro;F:Football,Fioretto,Fitness;G:Ginnastica,Golf,Go-kart;I:Immersione,Ippica;L:Lotta,Lancio del peso;M:Maratona,Motociclismo,Mountain bike;N:Nuoto,Nordic walking;O:Orienteering,Ostacoli;P:Pallavolo,Pallamano,Pattinaggio,Parkour;Q:Quidditch;R:Rugby,Roller,Running;S:Sci,Scherma,Surf,Skateboard;T:Tennis,Tuffi,Triathlon;U:Ultimate frisbee;V:Vela,Volley;Z:Zumba",
  bodypart:
    "A:Anca,Avambraccio,Alluce,Arteria;B:Braccio,Bocca,Bacino;C:Caviglia,Cuore,Collo,Coscia;D:Dito,Dorso,Diaframma;E:Esofago,Epidermide;F:Fegato,Fronte,Femore;G:Gamba,Ginocchio,Gomito,Gola;I:Intestino,Iride;L:Lingua,Labbro,Lobo;M:Mano,Milza,Muscolo,Mento;N:Naso,Nervo,Nuca;O:Occhio,Orecchio,Osso,Ombelico;P:Piede,Polmone,Pollice,Pelle;R:Rene,Rotula,Retina;S:Spalla,Stomaco,Schiena,Sopracciglio;T:Testa,Tibia,Torace,Tallone;U:Ulna,Unghia,Ugola;V:Vena,Vertebra,Ventre;Z:Zigomo",
  object:
    "A:Ancora,Armadio,Accendino;B:Bottiglia,Borsa,Bicchiere,Bottone;C:Chiave,Coltello,Cuscino,Candela;D:Divano,Diario;E:Elmetto,Elastico;F:Forchetta,Finestra,Forbici;G:Gomma,Guanto,Giornale;I:Imbuto,Interruttore;L:Lampada,Libro,Lenzuolo;M:Martello,Matita,Mappa;N:Nastro,Nave;O:Ombrello,Orologio,Occhiali;P:Penna,Piatto,Pentola,Portafoglio;Q:Quaderno,Quadro;R:Radio,Righello,Rubinetto;S:Sedia,Specchio,Scatola,Scarpa;T:Tavolo,Tazza,Telefono,Tappeto;U:Utensile,Uncino;V:Vaso,Valigia,Ventilatore;Z:Zaino,Zucchero filato",
  clothing:
    "A:Abito,Anfibi,Accappatoio;B:Berretto,Blazer,Body;C:Camicia,Cappotto,Calze,Cintura;D:Dolcevita;E:Espadrillas;F:Felpa,Foulard;G:Giacca,Gonna,Guanti;I:Impermeabile,Infradito;L:Leggings,Lupetto;M:Maglietta,Maglione,Mutande;N:Niente,Nastro;O:Occhiali da sole,Orecchini;P:Pantaloni,Pigiama,Piumino,Polo;Q:Quadri;R:Reggiseno,Rimboccatura;S:Scarpe,Sciarpa,Stivali,Smoking;T:T-shirt,Tuta,Top;U:Uniforme;V:Vestito,Velo;Z:Zoccoli",
  carbrand:
    "A:Alfa Romeo,Audi,Aston Martin;B:BMW,Bentley,Bugatti;C:Citroen,Chevrolet,Cupra;D:Dacia,Dodge;F:Fiat,Ferrari,Ford;G:Genesis,GMC;H:Honda,Hyundai;I:Isuzu,Iveco,Infiniti;L:Lancia,Lamborghini,Land Rover,Lexus;M:Maserati,Mercedes,Mazda,Mini;N:Nissan;O:Opel;P:Porsche,Peugeot,Pagani;R:Renault,Rolls-Royce;S:Seat,Skoda,Subaru,Suzuki;T:Toyota,Tesla,Tata;V:Volvo,Volkswagen;Z:Zastava",
  drink:
    "A:Acqua,Aranciata,Amaro,Aperol;B:Birra,Bellini,Brandy;C:Caffè,Cappuccino,Chinotto,Cola;D:Daiquiri;E:Espresso;F:Frullato,Fernet;G:Ginepro,Gin tonic,Grappa;I:Idromele;L:Latte,Limoncello,Limonata;M:Marsala,Mojito,Moscato;N:Negroni,Nocino;O:Orzata,Orzo;P:Prosecco,Punch,Porto;R:Rum,Rosso,Rabarbaro;S:Spritz,Succo,Sambuca;T:Tè,Tequila,Tonica;V:Vino,Vodka,Vermouth;Z:Zabaione",
  hobby:
    "A:Arrampicata,Astronomia,Acquerello;B:Ballo,Bricolage,Birdwatching;C:Cucina,Ciclismo,Corsa,Canto;D:Disegno,Danza;E:Escursionismo,Equitazione;F:Fotografia,Fai da te;G:Giardinaggio,Gaming;I:Informatica,Immersioni;L:Lettura,Lego;M:Musica,Modellismo,Meditazione;N:Nuoto,Nordic walking;O:Origami,Orticoltura;P:Pittura,Pesca,Puzzle,Podcast;Q:Quilting;R:Ricamo,Running,Recitazione;S:Scacchi,Scrittura,Sci,Surf;T:Teatro,Trekking,Tennis;U:Ukulele;V:Viaggiare,Volontariato;Z:Zumba",
  subject:
    "A:Arte,Algebra,Astronomia;B:Biologia;C:Chimica,Cinese;D:Disegno,Diritto;E:Economia,Educazione fisica,Elettronica;F:Fisica,Filosofia,Francese;G:Geografia,Geometria,Ginnastica;I:Italiano,Inglese,Informatica;L:Latino,Letteratura,Lingue;M:Matematica,Musica;N:Naturali,Nuoto;O:Orchestra;P:Psicologia,Pedagogia;R:Religione,Russo;S:Storia,Spagnolo,Statistica,Scienze;T:Tecnologia,Teatro,Trigonometria;U:Urbanistica;Z:Zoologia",
  superhero:
    "A:Aquaman,Ant-Man;B:Batman,Black Panther,Black Widow;C:Capitan America,Catwoman;D:Deadpool,Devil,Dottor Strange;E:Elektra;F:Flash,Falcon;G:Gamora,Groot,Goldrake;I:Iron Man,Invisibile;L:Loki,Luke Cage;M:Magneto,Mystica;N:Nightwing,Nick Fury;O:Occhio di Falco;P:Professor X,Punisher;R:Robin,Rogue,Rocket;S:Superman,Spiderman,Scarlet Witch;T:Thor,Thanos,Tempesta;U:Ultron;V:Visione,Venom;W:Wolverine,Wonder Woman;Z:Zatanna",
  game:
    "A:Azul,Allegro chirurgo;B:Briscola,Burraco,Bingo;C:Carcassonne,Cluedo,Catan;D:Domino,Dama,Dixit;F:Forza quattro,Fantacalcio;G:Gioco dell oca,Go;I:Indovina chi;L:Lupus in Tabula,Labirinto;M:Monopoly,Memory,Mercante in fiera;N:Nascondino;O:Othello;P:Poker,Puzzle,Pictionary;Q:Quarto;R:Risiko,Rubamazzo,Rummikub;S:Scacchi,Scarabeo,Scala quaranta,Scopa;T:Tombola,Taboo,Twister;U:Uno,Ubongo;Z:Zombicide",
  instrument:
    "A:Arpa,Armonica,Arpicordo;B:Basso,Batteria,Banjo;C:Chitarra,Clarinetto,Contrabbasso,Corno;D:Didgeridoo;E:Eufonio;F:Flauto,Fisarmonica,Fagotto;G:Grancassa,Glockenspiel;L:Liuto,Lira;M:Mandolino,Marimba,Maracas;O:Organo,Oboe,Ocarina;P:Pianoforte,Piatti,Percussioni;S:Sassofono,Sitar,Sintetizzatore;T:Tromba,Tamburo,Triangolo,Trombone;U:Ukulele;V:Violino,Viola,Violoncello;X:Xilofono;Z:Zampogna",
  sweet:
    "A:Amaretto,Arancini di riso;B:Babà,Biscotto,Brownie;C:Cannolo,Cioccolato,Crostata,Caramella;D:Dolcetto,Donut;F:Frittella,Fudge;G:Gelato,Gianduiotto;I:Il tiramisù,Iris;L:Lecca-lecca,Liquirizia;M:Maritozzo,Marshmallow,Meringa;N:Nutella,Nougat;O:Oreo,Ovetto;P:Panettone,Pastiera,Profiterole;R:Ricciarelli,Rocher;S:Sfogliatella,Struffoli,Semifreddo;T:Torrone,Tiramisù,Torta;V:Vaniglia,Veneziana;Z:Zeppola,Zabaione,Zucchero filato",
  furniture:
    "A:Armadio,Attaccapanni;B:Bancone,Buffet;C:Cassettiera,Comodino,Credenza,Cuccia;D:Divano,Doppio letto;E:Etagere;F:Futon;G:Guardaroba;L:Letto,Libreria,Lampadario;M:Mensola,Madia,Materasso;O:Ottomana;P:Poltrona,Pensile,Panca;S:Sedia,Scrivania,Scaffale,Sgabello;T:Tavolo,Tavolino,Tappeto;V:Vetrina,Vassoio;Z:Zerbino",
  island:
    "A:Antigua,Aruba,Asinara;B:Bali,Barbados,Bermuda;C:Capri,Creta,Corsica,Cuba;D:Djerba,Dominica;E:Elba,Eolie;F:Favignana,Filicudi,Formentera;G:Giglio,Gran Canaria,Gotland;I:Ischia,Islanda,Irlanda,Ibiza;L:Lampedusa,Lanzarote,Lipari;M:Malta,Maiorca,Madagascar,Maui;N:Nantucket,Nuova Zelanda;O:Okinawa,Oahu,Orkney;P:Pantelleria,Ponza,Panarea;R:Rodi,Reunion,Rugen;S:Sicilia,Sardegna,Santorini,Stromboli;T:Tenerife,Tahiti,Tasmania;U:Ustica,Unst;V:Vulcano,Ventotene;Z:Zante,Zanzibar",
  capital:
    "A:Atene,Amsterdam,Ankara,Algeri;B:Berlino,Bruxelles,Budapest,Berna;C:Copenaghen,Canberra,Caracas;D:Dublino,Doha,Damasco;E:Erevan;F:Freetown;G:Georgetown,Gaborone;H:Helsinki,Hanoi,Harare;I:Islamabad;L:Londra,Lisbona,Lima,Lussemburgo;M:Madrid,Mosca,Manila,Minsk;N:Nairobi,Nuova Delhi,Nicosia;O:Oslo,Ottawa;P:Parigi,Praga,Pechino,Pretoria;Q:Quito;R:Roma,Riga,Riad,Reykjavik;S:Stoccolma,Seul,Sofia,Santiago;T:Tokyo,Tunisi,Tallinn,Teheran;U:Ulan Bator;V:Vienna,Vilnius,Valletta,Varsavia;Z:Zagabria",
  videogame:
    "A:Among Us,Assassins Creed,Apex Legends;B:Battlefield,Bloodborne;C:Call of Duty,Counter-Strike,Cyberpunk;D:Doom,Diablo,Dark Souls;E:Elden Ring;F:Fortnite,FIFA,Far Cry;G:GTA,God of War,Genshin Impact;H:Halo,Hades;I:It Takes Two;L:League of Legends,Last of Us;M:Minecraft,Mario Kart,Metroid;N:Need for Speed;O:Overwatch,Oblivion;P:Pokemon,Portal,Pac-Man;R:Rocket League,Roblox;S:Super Mario,Sims,Skyrim;T:Tetris,Tomb Raider;U:Uncharted,Undertale;V:Valorant,Valheim;Z:Zelda,Zuma",
  tool:
    "A:Accetta,Avvitatore,Ascia;B:Bulino,Brugola;C:Cacciavite,Chiave inglese,Cesoia;D:Demolitore;E:Estrattore;F:Forbici,Fresa,Filo a piombo;G:Grimaldello,Guanti da lavoro;I:Incudine;L:Lima,Livella,Lampada da lavoro;M:Martello,Metro,Morsa,Mazza;N:Nastro isolante;P:Pinza,Pialla,Piccone,Punteruolo;R:Raspa,Righello,Rullo;S:Sega,Scalpello,Smerigliatrice,Spatola;T:Trapano,Tenaglia,Taglierino;V:Vanga,Vite;Z:Zappa",
  feeling:
    "A:Amore,Ansia,Allegria,Ammirazione;B:Beatitudine,Bisogno;C:Coraggio,Curiosità,Calma,Colpa;D:Delusione,Disgusto,Desiderio;E:Entusiasmo,Euforia,Empatia;F:Felicità,Frustrazione,Fiducia;G:Gioia,Gelosia,Gratitudine;I:Invidia,Imbarazzo,Inquietudine;L:Libertà,Languore;M:Malinconia,Meraviglia,Motivazione;N:Nostalgia,Noia,Nervosismo;O:Ottimismo,Orgoglio;P:Paura,Pace,Passione,Panico;R:Rabbia,Rimpianto,Rimorso;S:Serenità,Sorpresa,Solitudine,Speranza;T:Tristezza,Tenerezza,Tensione;U:Umiltà,Urgenza;V:Vergogna,Vitalità;Z:Zelo",
  generic:
    "A:Albero,Acqua,Aria,Angolo,Amico;B:Barca,Bosco,Bicchiere,Banco;C:Casa,Cielo,Campo,Chiave,Carta;D:Denaro,Disegno,Dado,Dente;E:Erba,Estate,Eco,Entrata;F:Fiore,Fuoco,Finestra,Foglia;G:Giardino,Gioco,Gatto,Ghiaccio;I:Isola,Idea,Inverno,Incontro;L:Luna,Lago,Luce,Libro;M:Mare,Monte,Mano,Mattina;N:Notte,Nuvola,Nido,Nome;O:Ombra,Onda,Orto,Oro;P:Ponte,Porta,Pietra,Piazza;Q:Quadro,Quiete;R:Rete,Ruota,Radice,Riva;S:Sole,Stella,Strada,Sogno;T:Terra,Tetto,Treno,Tempo;U:Uomo,Uscita,Uva;V:Vento,Voce,Viaggio,Valle;Z:Zaino,Zona,Zucchero",
};
